### ISSUE TITLE
Inserted area upgrades keep disappearing

### ISSUE THREAD

**Issue by rafaelhr** [TheMillman/FarmingUtils#1]
After I changed the config for "Crop Farmer Tick", my crop farmers started making any area upgrades I put into them disappear. That started happening as soon as I changed "Crop Farmer Tick" from 40 to 20. The problem doesn't fix itself if I return the config to its default value.

Minecraft 1.18.1
Forge 39.0.75
Farming Utils 0.1.0

**Comment by TheMillman** [comment]
I'll try to fix this today as soon as I can. Thank you for reporting this bug to me.

**Comment by TheMillman** [comment]
I tried to recreate the bug but everything works for me, could you send me the mods list and the log. Thank you.

**Comment by rafaelhr** [comment]
I found out what was wrong, it wasn't actually a bug at all, just a stupid error on my part. I was importing the upgrades from the farmers to my Refined Storage network. I apologize for wasting your time.

**Comment by TheMillman** [comment]
There is no problem, I was already planning to do an update, I took the opportunity to improve the code a little.
Glad to know it works.
