### ISSUE TITLE
Hard crash when trying to harvest canola from ultimate car mod[1.18.2]

### ISSUE THREAD

**Issue by SDUBZ** [TheMillman/FarmingUtils#3]
forge:1.18.2-40.1.20
farm utils: farmingutils-1.18.2-0.1.1
TML: themillmanlib-1.18.2-0.0.13
UCM: car-1.18.2-1.0.3

[crash-2022-05-22_23.29.28-client.txt](https://github.com/TheMillman/FarmingUtils/files/8749632/crash-2022-05-22_23.29.28-client.txt)

**Comment by TheMillman** [comment]
Thanks, I'll solve it as soon as I can.

**Comment by TheMillman** [comment]
Ho risolto il problema, ho creato un tag, si chiama age_3_crops, basta aggiungere qui tutti i semi con 3 stadi di crescita. In futuro cercherò di migliorare la cosa.

**Comment by TheMillman** [comment]
I solved the problem, I created a tag, it is called age_3_crops, just add all the seeds with 3 growth stages here, like canola seeds and it should work, in the future I will try to improve it.

**Comment by TheMillman** [comment]
I also leave you the datapack.
[FarmingUtilsCompat.zip](https://github.com/TheMillman/FarmingUtils/files/8793558/FarmingUtilsCompat.zip)
